# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "bootstrap.sh"
  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
    node.vm.box               = "debian/buster64"
    node.vm.hostname          = "kmaster.local"
    node.vm.network "private_network", ip: "172.16.16.100"
    node.vm.provider :virtualbox do |v|
      v.name    = "kmaster"
      v.memory  = 2048
    end
    node.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end
  # Kubernetes Worker Nodes
  NodeCount = 2
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |node|
      node.vm.box               = "debian/buster64"
      node.vm.hostname          = "kworker#{i}.local"
      node.vm.network "private_network", ip: "172.16.16.10#{i}"
      node.vm.provider :virtualbox do |v|
        v.name    = "kworker#{i}"
        v.memory  = 1024
        v.cpus    = 1
      end
     node.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end
end
